<div id="reportlinks">
	<a href="#" onclick="update_div('#ajax','reports/list_escalated_tickets.php');"><img src="/public/images/ICONS-escalated@2x.png" alt="View escalated tickets" title="View escalated tickets"  width="24" height="25" />Escalated tickets</a>
	<a href="#" onclick="update_div('#ajax','reports/list_unassigned_tickets.php');"><img src="/public/images/ICONS-unassigned@2x.png" alt="View unassigned tickets" title="View unassigned tickets"  width="24" height="25" />Unassigned tickets</a>
	<a href="#" onclick="update_div('#ajax','reports/list_open_tickets.php');"><img src="/public/images/ICONS-assigned@2x.png" alt="View Assigned tickets" title="View Assigned tickets"  width="24" height="25" />Assigned tickets</a>
	<a href="#" onclick="update_div('#ajax','reports/list_open_and_unassigned_tickets.php');"><img src="/public/images/ICONS-view@2x.png" alt="View Open tickets" title="View Open tickets"  width="24" height="25" />Open tickets</a>
	<a href="#" onclick="update_div('#ajax','reports/list_closed_tickets.php');"><img src="/public/images/ICONS-closed@2x.png" alt="View closed tickets" title="View closed tickets"  width="24" height="25" />Closed tickets</a>
	<a href="#" onclick="update_div('#ajax','reports/list_all_tickets.php');"><img src="/public/images/ICONS-allcalls@2x.png" alt="View all tickets" title="View all tickets"  width="24" height="25" />All tickets</a>
	<a href="#" onclick="update_div('#ajax','reports/view_oldest_ticket.php');"><img src="/public/images/ICONS-oldestcall@2x.png" alt="View oldest ticket" title="View oldest ticket"  width="24" height="25" />Oldest ticket</a>
	<a href="#" onclick="update_div('#ajax','reports/list_sent_away_tickets.php');"><img src="/public/images/ICONS-sentaway@2x.png" alt="Sent away for repair" title="Sent away for repair"  width="24" height="25" />Sent away</a>
	<a href="#" onclick="update_div('#ajax','reports/list_hold_tickets.php');"><img src="/public/images/ICONS-hold@2x.png" alt="On Hold" title="On Hold"  width="24" height="25" />On Hold</a>	
	<a href="#" onclick="update_div('#ajax','reports/view_work_rate.php');"><img src="/public/images/ICONS-workrate@2x.png" alt="Engineer work rate" title="Engineer work rate"  width="24" height="25" />Work rate</a>
	<a href="#" onclick="update_div('#ajax','reports/view_assigned_numbers.php');"><img src="/public/images/ICONS-assignnotclosed@2x.png" alt="View assigned numbers" title="View assigned numbers"  width="24" height="25" />Assigned numbers</a>
	<a href="#" onclick="update_div('#ajax','reports/view_punchcard.php');"><img src="/public/images/ICONS-punchcard@2x.png" alt="Punchcard" title="Punchcard"  width="24" height="25" />Punchcard</a>
	<a href="#" onclick="update_div('#ajax','reports/list_user_feedback.php');"><img src="/public/images/ICONS-userfeedback@2x.png" alt="User Feedback" title="User Feedback"  width="24" height="25" />User feedback</a>
	<a href="#" onclick="update_div('#ajax','reports/view_emerging_issues.php');"><img src="/public/images/ICONS-issues@2x.png" alt="Emerging issues" title="Emerging issues"  width="24" height="25" />Emerging issues</a>
	<a href="#" onclick="update_div('#ajax','reports/search_tickets.php');"><img src="/public/images/ICONS-search@2x.png" alt="Search tickets" title="Search tickets"  width="24" height="25" />Search tickets</a>
	<a href="#" onclick="update_div('#ajax','reports/view_change_control.php');"><img src="/public/images/ICONS-changecontrol@2x.png" alt="View change control" title="View change control"  width="24" height="25" />Change control</a>
	<a href="#" onclick="update_div('#ajax','reports/view_lockers.php');"><img src="/public/images/ICONS-lockers@2x.png" alt="Lockers" title="Lockers"  width="24" height="25" />Lockers</a>
	<a href="#" onclick="update_div('#ajax','reports/list_scheduled_tasks.php');"><img src="/public/images/ICONS-scheduledtask@2x.png" alt="scheduled tasks" title="sheduled tasks"  width="24" height="25" />Scheduled tasks</a>
	<a href="#" onclick="update_div('#ajax','reports/graph_reason_behind.php');"><img src="/public/images/ICONS-reason@2x.png" alt="reason behind issue" title="reason behind issue"  width="24" height="25" />Reason behind issue</a>
	<a href="#" onclick="update_div('#ajax','reports/list_all_outofhours.php');"><img src="/public/images/ICONS-outofhours@2x.png" alt="Out Of Hours" title="Out Of Hours"  width="24" height="25" />Out Of Hours</a>
	<a href="#" onclick="update_div('#ajax','reports/list_tickets_awaiting_invoice.php');"><img src="/public/images/ICONS-invoice@2x.png" alt="awaiting invoice" title="awaiting invoice"  width="24" height="25" />Awaiting invoice</a>
	<a href="#" onclick="update_div('#ajax','reports/view_digital_screen.php');"><img src="/public/images/ICONS-digitalscreen@2x.png" alt="IT reception screen" title="IT reception screen"  width="24" height="25" />TV screen</a>
</div>